### ISSUE TITLE
Create a 2D camera library

### ISSUE THREAD

**Issue by TiagoJSM** [TiagoJSM/Arx#14]
Creat a 2D camera with the following requirements:
- Has a GameObject target
- Follow the GameObject target with configurable delay
- Responds to triggers to change it's target

**Comment by TiagoJSM** [comment]
Done all of the requirements and implemented some zones, for zoom, scene bounds and new target zones, if new ones are needed they can be added later

**Comment by lamuria** [comment]
Hi there,

Where is the pull request with the solution to this issue?

**Comment by TiagoJSM** [comment]
I didn't made it, merged into master
